/**
 * Takes a random prohpecy and returns it.
 * 
 * @example
 * ```
 * import { foretell } from 'obnoxious-oracle';
 * let test = foretell();
 * console.log(test); // => "WON'T WORK ON IE8"
 * ```
 * @returns string
 */
export function foretell() {
    return PROPHECIES[Math.floor(Math.random() * PROPHECIES.length)];
}


/**
 * List of all prophecies.
 */
export const PROPHECIES: string[] = [
    "THIS WAS A MISTAKE",
    "WHY HAVE I DONE THIS",
    "WHY ARE YOU HERE",
    "PRESENTED IN BC [BRAIN CONTROL]",
    "LOADING...",
    "CONDEMNED BY THE POPE",
    "PROUDLY MADE ON EARTH",
    "NOT Y3K COMPLIANT",
    "NOT Y2K38 COMPLIANT",
    "FROM THE MAKERS OF THIS PRODUCT",
    "THE WEB THAT SITES BACK",
    "NOMINATED FOR 0 AWARDS",
    "A WARNING OF THINGS TO COME",
    "TOUCH EYEBALLS TO SCREEN FOR CHEAP LASER SURGERY",
    "NOT A SUBSTITUTE FOR HUMAN INTERACTION",
    "NOT FDA APPROVED",
    "NOT A REAL PRODUCT",
    "SOURCE CODE DECIPHERED FROM CROP CIRCLES",
    "MADE WITH LOVE AND DEPRESSION",
    "BANNED IN 15 US STATES",
    "FOR PROPER EXPERIENCE, TAKE RED PILL NOW",
    "SCRATCH HERE TO REVEAL PRIZE",
    "WON'T WORK ON IE8",
    "KNOWN TO CAUSE INSANITY IN LABORATORY MICE",
    "THE PROUD RESULT OF PRISON LABOR",
    "d2h5IGFyZSB5b3UgcmVhZGluZyB0aGlz",
    "THE FLAMES IN YOUR PC ARE NOT INTENTIONAL",
    "CURRENT EBAY BID: $5.13",
    "PUT ON 3-D MONOCLE NOW",
    "NOW WITH 2 PIXELS PER PIXEL",
    "#1 MOST VIEWED PAGE BY AI WEBSCRAPERS",
    "WE'RE FOLLOWING YOU, BUT NOT ON TWITTER",
    "ASK YOUR DOCTOR IF THIS IS RIGHT FOR YOU",
    "MADE FROM 95% RECYCLED PIXELS",
    "WARNING: DO NOT SHOW TO HORSES",
    "PUT ON 2-D GLASSES NOW",
    "ONE OF THE 7! WONDERS OF THE WORLD",
    "THIS WEBSITE PREVENTS RIGHT CLICKING AND SAVING",
    "WE'RE EVALUATING ALL USER INPUT",
    "AVALIABLE AT THE NEAREST METAVERSE",
    "SHOUTOUT TO GAY PEOPLE",
    ":D",
    "LETS CONVINCE JEFF BEZOS HIS NAME IS JEFF BENZOS",
    "BROUGHT TO YOU BY TED KACZYNSKI",
    "MWAHAHA! YOU'VE BEEN MINTED TO THE BLOCKCHAIN!",
    "THE CDC DOESN'T RECOMMEND PLAYING LEAGUE OF LEGENDS",
    "I BEEN HACKED, ALL MY APES GONE.",
    "BIG ICE COME IN. BIG ICE COME IN.",
    "THIS IS A CERTIFIED HOOD CLASSIC",
    "THE POPE LISTENED TO MEGALOVANIA",
    "MADE BY THE NICHEST INTERNET MICROCELEBRITIES",
    "GARFIELD IS BASICALLY NECO ARC",
    "[MESSAGE REMOVED BY ADMIN]",
    "CAPYBARA? CAPYBARA! COCONUT DOGGY!",
    "FOR A FREE GAY TEST, TURN OFF SCREEN AND TAKE A LOOK",
    "CARBON MONOXIDE IS AN ODORLESS GAS",
    "AS THE AUTHOR, I RATE THIS PLACE 10/10",
    "PROBLEM?",
    "NOT FOR MUSK CULTISTS",
    "THE FOG IS COMING. THE FOG IS COMING. THE FOG IS",
    "YOU SHOULD LOVE YOURSELF NOW!",
    "THIS WEBSITE SUPPORTS TRANS RIGHTS",
    "DO YOU REALLY THINK YOU WILL ESCAPE GODS JUDGEMENT",
    "BECOME UNGOVERNABLE",
    "TIME ISN'T REAL. WE'RE RELIVING THE SAME YEAR.",
    "YOU'RE DESERVING OF LOVE.",
    "I'M SORRY FOR EVERYTHING THAT HAS HAPPENED TO YOU",
    "IT'S GOING TO BE OK.",
    "NOW STARING TOM HOLLAND AND CHRIS PRATT",
    "IF YOU STAN MUSK YOU'RE CRINGE AND FATHERLESS",
    
]